# Generated by Django 2.2.7 on 2019-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_remove_viaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
