# Generated by Django 2.2.7 on 2019-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20191124_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
